### ISSUE TITLE
使用Latex相关

### ISSUE THREAD

**Issue by skyel1u** [firmianay/CTF-All-In-One#10]
我们可以用这个Latex模板：[https://github.com/GGolbik/GGLaTeXBookTemplate](https://github.com/GGolbik/GGLaTeXBookTemplate). 简单看了下，使用XeLatex编译，字体使用Google Noto Sans SC，还是可以的。

随便生成了一个PDF Demo，看看这个怎么样？
[zip.pdf](https://github.com/firmianay/CTF-All-In-One/files/1625472/zip.pdf)

**Comment by skyel1u** [comment]
目前使用该模板，图片因为大小不一致，排版可能影响美观

**Comment by firmianay** [comment]
所以居中？

**Comment by skyel1u** [comment]
目前bug：图片、表格还需仔细调整排版（还是我太菜

**Comment by skyel1u** [comment]
https://github.com/WisdomFusion/latex-templates
这个模板不错

**Comment by firmianay** [comment]
@skyel1u 可以，就靠你了

**Comment by skyel1u** [comment]
可能吗？
咕咕咕


Skye@XDSEC

**Comment by skyel1u** [comment]
换模版了换模版了，之前模板坑太多（插入图片很爆炸，没有好看的代码高亮），还是这个好看https://github.com/WisdomFusion/latex-templates/tree/master/progbookcn。
鉴于未来几个月或者未来的一年零几个月这个人忙于考研，咕咕咕。等忙完事情把这玩意搞起来（

**Comment by skyel1u** [comment]
Markdown是用css渲染的...导出html当然没问题，然而导出tex文件的话，对于一些复杂的格式比较麻烦(Pandoc也不是万能的)，我的想法是直接LaTeX重排版一遍，顺便校对一下有没有错误or能否在当前环境下复现。

一个小例子：![SKYE_2018-08-27_22-02-53.jpg](https://i.loli.net/2018/08/27/5b8404f54875a.jpg)

**Comment by inkydragon** [comment]
(我就应该把 HTML 放到 more 里面)，我觉得 pandoc 好还是因为他省去了手工转化的这步，自动化起来方便。markdown 一共也没几种标记，手工转化大多数时候还是在 copy&paste，之前我还想着写个脚本干这个事情，然后就找到了 pandoc。还有一点就是能转 ePub 继续折腾一下就能在手机上看了，想着挺好，虽然搜了一下有兼容性的大坑。

ReLaXed 确实是漂亮，不过写起来就有点麻烦了。

**Comment by firmianay** [comment]
latex计划因无人支持已终止
