### ISSUE TITLE
GitBook 内的链接跳转有问题

### ISSUE THREAD

**Issue by BDZNH** [firmianay/CTF-All-In-One#13]
https://firmianay.gitbooks.io/ctf-all-in-one/content/
这里显示的应该是仓库的README.md
在GitBook内点击跳转到SUMMARY.md，CONTRIBUTION.md，FAQ.md是不会跳转的。

**Comment by firmianay** [comment]
emmm对，因为这几个文件并没有被抓到GitBook里。Thx
