### ISSUE TITLE
第11章堆利用 11.1小节 glibc堆概述的一个问题

### ISSUE THREAD

**Issue by zambery** [firmianay/CTF-All-In-One#46]
第11章堆利用中11.1小节 glibc堆概述在描述`PREV_INUSE`标识的时候，说该标识位为1时，表示上一个chunk处于释放状态，否则表示上一个chunk处于使用状态。这里是不是描述反了，应该是1表示使用，0表示释放吧（微信读书上的电子版）
![image](https://user-images.githubusercontent.com/51513888/161664632-eeddcae4-a4c6-405d-aa95-a147957a4e7e.png)

**Comment by firmianay** [comment]
嗯对，纸质的已经纠正了，电子的不知道咋弄
https://github.com/firmianay/ctf-book
