### ISSUE TITLE
不能访问？

### ISSUE THREAD

**Issue by n-WN** [firmianay/CTF-All-In-One#51]
这个地址不能访问了 
https://firmianay.gitbooks.io/ctf-all-in-one/content/doc/

仓库指向的 https://firmianay.gitbook.io/ctf-all-in-one/6_writeup
可以访问
不过我昨天还在访问gitbooks这个网站

**Comment by firmianay** [comment]
好像很久之前就没有gitbooks了

**Comment by n-WN** [comment]
> 好像很久之前就没有gitbooks了

ook
