### ISSUE TITLE
Markdown 渲染不支持数学公式

### ISSUE THREAD

**Issue by sa1utyeggs** [firmianay/CTF-All-In-One#53]
以下这段 markdown：
=====================
例子： 今天是8/15 当前的时间区间为 7/15~8/15；上一个时间周期为 6/15~7/15；

分别获取两个时间周期内的平均值 $$ Avg_{7/15-8/15} $$ 与 $$ Avg_{6/15-7/15} $$

计算公式为：

$$ \cfrac{Avg_{7/15-8/15} - Avg_{6/15-7/15}}{Avg_{6/15-7/15}} * 100% $$
=====================
在 amis 中无法被渲染成功：
![image](https://github.com/firmianay/CTF-All-In-One/assets/63895563/e9a2d385-742a-49a7-a7e2-f35b41435979)

理想的状态：
![image](https://github.com/firmianay/CTF-All-In-One/assets/63895563/bed8998b-444e-4ee7-a03b-a55c35dfaa83)

希望增加支持 :)

**Comment by firmianay** [comment]
感谢师傅，渲染有问题的地方可以直接PR，我来合并就行
